### ISSUE TITLE
STAGE tokens aren't supported (snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#1095]
eg:
```
> python -c 'import sqlglot; sqlglot.parse_one("CREATE STAGE foobar", read="snowflake");'
...
sqlglot.errors.ParseError: Expected {<TokenType.VIEW: 'VIEW'>, <TokenType.COLUMN: 'COLUMN'>, <TokenType.TABLE: 'TABLE'>, <TokenType.SCHEMA: 'SCHEMA'>, <TokenType.PROCEDURE: 'PROCEDURE'>, <TokenType.INDEX: 'INDEX'>, <TokenType.FUNCTION: 'FUNCTION'>}. Line 1, Col: 8.
  CREATE STAGE foobar
```
see https://docs.snowflake.com/en/sql-reference/sql/create-stage.html

sqlglot 10.6.1

**Comment by tobymao** [comment]
all unrecognized createables will be parsed as commands now. full parsing of all CREATE statements is not what i'd consider high priority scope. so i would accept PRs to add full parsing, but it's nothing something the core team will spend time on

**Comment by tekumara** [comment]
would it make sense if I raised a PR that defines CREATABLES for specific dialects? (I'm not sure what you mean here by full parsing)

**Comment by GeorgeSittas** [comment]
> would it make sense if I raised a PR that defines CREATABLES for specific dialects

Not sure what you mean here, because `CREATABLES` is already defined in the base `Parser` class, so you can override it in other dialects if you need to.

> I'm not sure what you mean here by full parsing

SQLGlot can "understand" some `CREATE ...` statements better than others. The parsing logic for these is inside `_parse_create` and `CREATABLES` essentially defines the tokens corresponding to these statements. This is what Toby means by "full" parsing.

For those statements that SQLGlot doesn't yet have a specialized parsing logic, it just parses them as "Command" expressions, which means that it essentially stores the raw string of the statement instead of actually parsing their syntax.

**Comment by tekumara** [comment]
thank you for the explanation!

> so you can override it in other dialects if you need to.

yes this is what i was thinking of doing for the snowflake dialect, and raising a PR if that would be helpful?

**Comment by GeorgeSittas** [comment]
What do you want to support?

**Comment by tekumara** [comment]
`create database x` in snowflake is the main one, but I could add other snowflake-specific createables too.

**Comment by GeorgeSittas** [comment]
You can do that, or you can just add it to the base parser directly in order to reuse the `_parse_create` method. It seems like there's overlap in snowflake's syntax and what we can already handle.

https://docs.snowflake.com/en/sql-reference/sql/create-database

**Comment by tekumara** [comment]
here's my attempt to do some basic parsing of CREATE DATABASE in the same way as CREATE SCHEMA https://github.com/tobymao/sqlglot/pull/1230
