### ISSUE TITLE
How is replace figuring out which column to replace?

### ISSUE THREAD

**Issue by jeffwong** [tobymao/sqlglot#1492]
Hi, new user here.

I have a use case where a function is generating an expression. I want to join that to another table, and replace a column using a variable from the joined table.

I see the example in the docs 

```
tree = Select().select("x").select("y").from_("tbl")
tree.find(Column).replace(Column(this="z"))
print(tree.sql())
```

How does `replace` know to replace x with z? Instead of y with z?

My actual use case is to do something like

```
tree = Select().select("x").select("y").from_("tbl").join("select y2 from foo")
tree.find(Column).replace(Column(this="y2")) 
print(tree.sql())
```

and I hope to get something like this where y got replaced with y2, instead of x.

```
SELECT
  x,
  y2
FROM tbl
JOIN (
  SELECT
    y2
  FROM foo
)
```

**Comment by GeorgeSittas** [comment]
Hey @jeffwong!

> How does replace know to replace x with z? Instead of y with z?

It doesn't "know" anything; `replace` simply replaces an expression (node in the AST) with another expression. Here, the expression it's called on is whatever `find` returns, which happens to be `x` because it's the first column it finds. If you reverse the order of the selects, it will replace `y` instead.

For your use case, you can try using the `transform` method instead. The code would look something like:

```python
tree = Select().select("x").select("y").from_("tbl").join("select y2 from foo")
tree.transform(lambda node: Column(this="y2") if isinstance(node, Column) and node.name == "y" else node, copy=False)
print(tree.sql())
```
