### ISSUE TITLE
Expression line number

### ISSUE THREAD

**Issue by MaxHalford** [tobymao/sqlglot#1612]
**Is your feature request related to a problem? Please describe.**

I would like to know the line number of each expression.

**Describe the solution you'd like**

Ideally, each `Expression` would have an extra `lineno` attribute, a bit like what is done in the `ast` module [here](https://docs.python.org/3/library/ast.html#ast.AST.lineno).

**Describe alternatives you've considered**

I'd be ok using an alternative way, maybe by using the expression position in the string. But I can't figure out how to do that, even after reading the docs.

**Additional context**

I'm working towards automatically connecting code comments to fields. sqlglot doesn't seem to parse code comments, but those are easy enough to extract anyway. If I'm able to extract code comments, and field names, along with line numbers, I should be able to associate the two together. Albeit in a hacky way.

**Comment by GeorgeSittas** [comment]
Can you provide an example for what you're trying to do? SQLGlot doesn't parse comments (it's a hard thing to do and I'm not even sure if it's possible to do it in a generic way), but it does store them in AST nodes so that it can print them @ transpilation time.

I'm not sure how easy would be to store the line numbers correctly / exactly.

**Comment by tobymao** [comment]
i’ll look into this but the line numbers won’t be 100% accurate there’s no way to exactly map the two.

tokens have line and colin number but not ast nodes

so i may or may not implement this

**Comment by tobymao** [comment]
I just saw that you’re looking to extract for comments. Code comments are stored in the nodes in a best effort way as @GeorgeSittas mentioned. What exactly did you mean by sqlglot doesn’t parse comments?

**Comment by tobymao** [comment]
i'm going to close this for now as i don't think we'll be adding line numbers to expressions since they don't really map.

a couple of suggestions for you:

1. just use the tokenizer, the tokenizer has a one to one mapping with the text and also captures comments
2. check for comments in the expression nodes, the expression nodes have comments attached to them
3. subclass the parser and figure out some heuristic to attach the token to an expression

happy to chat more on this topic, feel free to join the slack channel if you wanna chat in depth

**Comment by MaxHalford** [comment]
> just use the tokenizer, the tokenizer has a one to one mapping with the text and also captures comments

Is this the case for all dialects? See the following example.

```py
import sqlglot

sql = """
SELECT
  customer_id,
  -- total amount spent
  SUM(order_total) AS total_spent
FROM
  orders
WHERE
  order_date >= '2022-01-01'
GROUP BY
  customer_id
"""
dialect = sqlglot.Dialect.get_or_raise('bigquery')()
dialect.tokenizer.tokenize(sql)
```

```
[<Token token_type: TokenType.SELECT, text: SELECT, line: 2, col: 1>,
 <Token token_type: TokenType.VAR, text: customer_id, line: 3, col: 3>,
 <Token token_type: TokenType.COMMA, text: ,, line: 3, col: 14>,
 <Token token_type: TokenType.VAR, text: SUM, line: 5, col: 3>,
 <Token token_type: TokenType.L_PAREN, text: (, line: 5, col: 6>,
 <Token token_type: TokenType.VAR, text: order_total, line: 5, col: 7>,
 <Token token_type: TokenType.R_PAREN, text: ), line: 5, col: 18>,
 <Token token_type: TokenType.ALIAS, text: AS, line: 5, col: 20>,
 <Token token_type: TokenType.VAR, text: total_spent, line: 5, col: 23>,
 <Token token_type: TokenType.FROM, text: FROM, line: 6, col: 1>,
 <Token token_type: TokenType.VAR, text: orders, line: 7, col: 3>,
 <Token token_type: TokenType.WHERE, text: WHERE, line: 8, col: 1>,
 <Token token_type: TokenType.VAR, text: order_date, line: 9, col: 3>,
 <Token token_type: TokenType.GTE, text: >=, line: 9, col: 14>,
 <Token token_type: TokenType.STRING, text: 2022-01-01, line: 9, col: 19>,
 <Token token_type: TokenType.GROUP_BY, text: GROUP BY, line: 10, col: 1>,
 <Token token_type: TokenType.VAR, text: customer_id, line: 11, col: 3>]
```

**Comment by GeorgeSittas** [comment]
Can you please point out the line(s) of interest? It's time-consuming to eyeball a token stream trying to find an issue.

**Comment by MaxHalford** [comment]
My bad. There is no line of interest. I can't see any COMMENT token in that token stream, even though the query has a comment in it.

**Comment by GeorgeSittas** [comment]
Gotcha, thanks for clarifying.

We don't produce `COMMENT` tokens, but rather attach the comments in tokens based on a few heuristics. In your example, there's this token in the produced token stream (checked it locally):

```
<Token token_type: TokenType.VAR, text: SUM, line: 5, col: 5, start: 49, end: 51, comments: [' total amount spent']>
```

Notice the `comments` attribute. We then try to pick them up at parse time and attach them to AST nodes using a best-effort approach, so that they're preserved at transpile time.

**Comment by MaxHalford** [comment]
Thanks a ton, I wouldn't have figured that out. I think I understand enough now to continue by myself. Thanks a ton! I'll circle back if I have something valuable to contribute.

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/df5ecdbebcdce491031538f6baa0f87ec7eefee8
