### ISSUE TITLE
Cannot EXTRACT EPOCH in Trino (transpiled from Redshift)

### ISSUE THREAD

**Issue by pangyifish** [tobymao/sqlglot#1737]
```
sql = """
select DATE_PART(EPOCH,  '2023-01-01')
"""

converted_sql = sqlglot.transpile(sql, read="redshift", write="trino")[0]
print(converted_sql)


SELECT EXTRACT(EPOCH FROM '2023-01-01')
```

Trino error:` Invalid EXTRACT field: EPOCH'`

https://trino.io/docs/current/functions/datetime.html#extraction-function

**Comment by tobymao** [comment]
this is not trivial to do because date_part(epoch ...) is tricky

if it's a timestamp, then it's epoch seconds from epoch time, but if it's an interval then it's simply the seconds of the interval. that means that the type of the column is required, so a full proof transpilation cannot be done. i suggest you make a custom transform here as well

```python
def transform(node):
     if isinstance(node, exp.Extract) and node.this.name.upper() == "EPOCH":
        return exp.TimeStrToUnix(this=node.expression)
    return node

query.transform(transform)
````

this will find all EXTRACTs in your redshift (date_part ...), if you are extract epoch, it will convert the string input into a unix timestamp

feel free to join our slack if you want to discuss more

https://tobikodata.com/slack

**Comment by pangyifish** [comment]
That makes sense, thanks so much for the explanation and suggestions!
