### ISSUE TITLE
Cannot transpile `trino` to `postgres` when using Trino functions

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#1829]
Hi, 

sqlglot==13.3.0

When I run the below code snippet,
```
query = "SELECT COALESCE(ELEMENT_AT(MAP_FROM_ENTRIES(ARRAY[(51, '1')]), id), quantity) FROM my_table"
new_query = sqlglot.transpile(sql=query, read='trino', write='postgres')[0]
print(new_query)
```

 I get back the same input `query`.

**Output**
`SELECT COALESCE(ELEMENT_AT(MAP_FROM_ENTRIES(ARRAY[(51, '1')]), id), quantity) FROM my_table`

**Comment by SudarshanVS** [comment]
@GeorgeSittas Thank you for the quick fix.

I was looking into json objects and it looks like `MAP_FROM_ENTRIES(ARRAY[(51,2)])` could become `(json_object('{51,2}'))`. Is this maybe a more appropriate solution?

**Comment by GeorgeSittas** [comment]
This is definitely on a better direction compared to the `VALUES` approach, but it would only work if the `ARRAY` expression contains literal values, otherwise it wouldn't be possible to create a json string out of the (unknown) array elements.

Also, even with this scheme, it's not trivial to transpile your original code correctly, because 1) we need to search for the parents of the `map_from_entries` expression to find `element_at` and 2) the `element_at` call can't be just converted to an index lookup in the `json_object` expression: it'd need to be converted into a json element access operation (`->`). This also means that we'd need to search for other consumers of the returned map value and transpile them accordingly, which is a pain.

I don't feel like this is worth implementing right now. What do you think @tobymao?

**Comment by tobymao** [comment]
nah forget it

**Comment by SudarshanVS** [comment]
I see what you mean thanks for the explanation.
