### ISSUE TITLE
WITH expressions are incorrectly attached to INSERT/CREATE?

### ISSUE THREAD

**Issue by gtoonstra** [tobymao/sqlglot#1940]
**Before you file an issue**
- Check if the issue still exists on main 
Checked against latest main

**Fully reproducible code snippet**
This SQL with either INSERT or CREATE results in a tree hierarchy that does not qualify end to end, because the WITH statement is attached to the create or insert instead of the embedded SELECT.

```WITH cte AS (
        SELECT 
                d.a, 
                b + 1 AS c, 
                e.f 
        FROM 
                db1.d 
        INNER JOIN db2.e ON db1.d.a = e.a 
        WHERE db1.d.a = 1),
second_cte AS (
SELECT * FROM cte
)

INSERT x
SELECT 
        *
FROM
        second_cte```

The following code 
```
        qualified = qualify(
                expression=node,
                schema=schema,
                db="db1",
                catalog="s",
                dialect="bigquery",
        )
        print(repr(qualified))
```

Shows a hierarchy that doesn't fully qualify the SELECT statements end to end.
Code that fixes this is supplied in a draft PR, but because of my lack of knowledge of sqlglot, it is very likely not the correct way of solving this. So mostly looking for feedback/confirmation, in the hope that the correct solution for it is chosen. There are likely other statements that suffer from the same issue.

**Comment by GeorgeSittas** [comment]
Hey,

> This SQL with either INSERT or CREATE results in a tree hierarchy that does not qualify end to end, because the WITH statement is attached to the create or insert instead of the embedded SELECT.

This is not quite right. The corresponding expressions are not qualified because DDLs / DMLs are not currently "optimizable", as in we skip any non-`Unionable` expression when trying to create a scope for it, and so functions like `qualify` don't actually do anything for these expressions (besides possibly just adding quotes which doesn't require scope information).

I'm not sure if fixing this is a high priority, @tobymao what do you think?

**Comment by tobymao** [comment]
not in scope, happy to receive a pr
