### ISSUE TITLE
Trino `date_trunc` to Spark translate error

### ISSUE THREAD

**Issue by dmelchor-stripe** [tobymao/sqlglot#1947]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

Running:
```
sqlglot.transpile("date_trunc('day', DATE '2022-02-01')", read="trino", write="spark")[0]
```
Outputs:
```
"TRUNC(CAST('2022-02-01' AS DATE), 'day')"
```
When it should output
```
"DATE_TRUNC('day', CAST('2022-02-01' AS DATE))"
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

TRUNC:: https://spark.apache.org/docs/latest/api/sql/index.html#trunc
DATE_TRUNC: https://spark.apache.org/docs/latest/api/sql/index.html#date_trunc

**Comment by tobymao** [comment]
i don't think this is correct. trino date_trunc returns a date if the input is a date, and a timestamp if the input is a timestamp.

in spark, trunc returns a date and date_trunc returns a timestamp,

because in trino you're calling date_trunc(..., date ...) this is equivalent to the spark trunc version, for you to call date_trunc('day') on something at the date grain already doesn't make much sense. 

i believe the current behavior is correct, and your trino query doesn't seem to provide much value.
