### ISSUE TITLE
subquery unnesting optimization generates code with empty quote

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2327]
**Fully reproducible code snippet**

```
In [54]: import sqlglot as sg

In [55]: expr = sg.parse_one(
    ...:     "select t.x from t where (select s.y from s where t.x = s.z)", read="duckdb"
    ...: )

In [56]: import sqlglot.optimizer as sgo

In [57]: print(sgo.unnest_subqueries.unnest_subqueries(expr).sql("duckdb", pretty=True))
SELECT
  t.x
FROM t
LEFT JOIN (
  SELECT
    ARRAY_AGG(y),
    s.z AS _u_1
  FROM s
  WHERE
    TRUE
  GROUP BY
    s.z
) AS _u_0
  ON t.x = _u_0._u_1
WHERE
  _u_0.""
```

Perhaps I am using this in correctly?

**Official Documentation**

N/A

**Comment by GeorgeSittas** [comment]
There are dependencies between the optimizer rules, e.g. if you run the whole optimizer pipeline you get:

```python
>>> import sqlglot
>>> expr = sqlglot.parse_one("select t.x from t where (select s.y from s where t.x = s.z)", read="duckdb")
>>> print(optimize(expr, dialect="duckdb").sql("duckdb", pretty=True))
WITH "_u_0" AS (
  SELECT
    ARRAY_AGG("s"."y") AS "y",
    "s"."z" AS "_u_1"
  FROM "s" AS "s"
  GROUP BY
    "s"."z"
)
SELECT
  "t"."x" AS "x"
FROM "t" AS "t"
LEFT JOIN "_u_0" AS "_u_0"
  ON "t"."x" = "_u_0"."_u_1"
WHERE
  "_u_0"."y"
```

**Comment by cpcloud** [comment]
Do the dependencies affect whether the generated code is valid? I think `x.""` is invalid SQL.

**Comment by GeorgeSittas** [comment]
Yep, because it produces an invalid AST, which wouldn't have happened if the rules were executed in order. I'm not exactly sure why you see that behavior in this case, I'd need to dig deeper to understand that, but since the optimizer seems to work correctly I'll go ahead and close this as a non-issue for now.

**Comment by cpcloud** [comment]
In the long term I would like to be able to use the rules independently, not sure if that's in scope or not. Either way, thanks!

**Comment by GeorgeSittas** [comment]
Yeah that would definitely be ideal, but some rules require certain canonicalizing steps to be executed first (hence the dependency), otherwise the code would be more complex / error-prone. There are some rules like `qualify`, `simplify` and `annotate_types` that should be able to run as-is, though.
