### ISSUE TITLE
Comment uneeded DDL statements from Oracle to Spark transpiling

### ISSUE THREAD

**Issue by CaryMoore-DB** [tobymao/sqlglot#2357]
when transpiling from Oracle to Spark, the multitude of additional Oracle DDL statements are causing the sqlglot to fail instead of simply not carrying them forward to the new code.  I have to remove from `"SEGMENT CREATION IMMEDIATE...TABLESPACE "SAMPLE" ;` to have the code execute.  Perhaps a better way is to simply comment them if not recognized.  DDL Sample below:

```
CREATE TABLE "SAMPLE_TABLE"
( "SAMPLE_TEXT_FIELD" VARCHAR2(5 BYTE),
  "SAMPLE_DATE_FIELD" DATE
) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 52428800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAMPLE" ;
```

**Comment by GeorgeSittas** [comment]
DDL statements are generally harder to transpile across different dialects correctly, mostly due to the many different options provided by the corresponding engines. I think the dialects that have better support for DDL transpilation are currently Hive, Spark, DataBricks, T-SQL and possibly a few more I'm forgetting.

Oracle in particular hasn't been a high priority for us, which is why many of these options are missing. It's not in scope for us to improve the transpilation of Oracle DDL statements, but we'll be happy to accept high-quality PRs.

I'm going to close this issue as not planned for now, but you can reach out in Slack if you want to work on this and need guidance.

cc: @tobymao
