### ISSUE TITLE
Support lineage through a LATERAL FLATTEN from clause in Snowflake

### ISSUE THREAD

**Issue by edpaget** [tobymao/sqlglot#2413]
**Is your feature request related to a problem? Please describe.**
I have a Snowflake SQL query like `SELECT VALUE FROM TABLE_A, LATERAL FLATTEN(TABLE_A.VARIANT_COLUMN)`. I would like to be able to use the `lineage` function to get the lineage tree of the column "VALUE" (in case TABLE_A is actually a subquery, cte, etc).

**Describe the solution you'd like**
lineage should understand that VALUE's lineage is through TABLE_A.VARIANT_COLUMN (or through a subquery or CTE in place of TABLE_A). The `FLATTEN` function, when the Snowflake dialect is selected, should be treated as a select expression that adds the columns documented as [its output](https://docs.snowflake.com/en/sql-reference/functions/flatten#output).

The lineage tree of value should look something like VALUE -> FLATTEN(TABLE_A>VARIANT_COLUMN) -> TABLE_A.VARIANT_COLUMN -> TABLE_A. 

**Describe alternatives you've considered**
My plan was to have the Snowflake dialect parser produce a TableAlias expression when it parses a FLATTEN function populated with with the columns produces by the expression. Right now a TableAlias is produced, but it has no columns, so lineage fails raising a ValueError.

I'm happy to work on this feature if it's something you want to support in sqlglot but wanted to open this issue to make sure my suggestion of an implementation strategy make sense and is something you'd accept.

**Comment by GeorgeSittas** [comment]
I see, what you're suggesting looks reasonable. Just one comment on this:

> My plan was to have the Snowflake dialect parser produce a TableAlias expression when it parses a FLATTEN function populated with with the columns produces by the expression. Right now a TableAlias is produced, but it has no columns, so lineage fails raising a ValueError.

I'm not sure if we want to touch Snowflake's parser for this, even though we could. My initial reaction was that this can be solved by adding extra logic to the `qualify_tables` rule in order to emit a `TableAlias` with additional info, i.e. the output columns specified in Snowflake's docs. The downside to this is that we pollute the rule with Snowflake-specific logic, because there's no other way to parameterize how we do stuff per dialect in the optimizer currently.

@tobymao what do you think?

**Comment by tobymao** [comment]
shouldn't this be done in qualify_columns? it already deals with table column aliases

**Comment by GeorgeSittas** [comment]
Not sure, what do we gain from doing it there? I figured that `qualify_tables` would allow it to just work for the rest of the optimizer rules.
