### ISSUE TITLE
qualify expands alias which causes issues in where clause

### ISSUE THREAD

**Issue by as-sher** [tobymao/sqlglot#2508]
`expand_alias_refs`
Do you think we can control this param not to update the columns in the where clause since it is causing problems?

Input
`select sum(t) as abc, abc from test where abc>1`

Transpiled with qualify
```
SELECT SUM(test.t) AS abc,
       SUM(test.t) AS _col_1
FROM test AS test
WHERE SUM(test.t) > 1
```
this causes an issue as the aggregate function is not supported in the where clause

**Comment by GeorgeSittas** [comment]
Closing this for now since Redshift (input dialect -- see Slack) treats this query as invalid (see image below). Aggregates are computed after the `WHERE` clause so this checks out, unless the intention of the query is different.

@as-sher please provide some more context (e.g. docs) for future issues. Happy to reopen this one or continue chatting if there's an actual issue I missed.

![image](https://github.com/tobymao/sqlglot/assets/46752250/839056ad-1d11-4124-a58e-793539ea0717)
