### ISSUE TITLE
Getting a line number and column or AST nodes

### ISSUE THREAD

**Issue by erezsh** [tobymao/sqlglot#2580]
**Is your feature request related to a problem? Please describe.**

I want to be able to report the line number and column of certain AST nodes (i.e. instances of Expression), such as Identifier etc.

**Describe the solution you'd like**
I would like this information, that can be calculated from the Tokens, to be present in the AST nodes. For example, in the meta attribute, or something similar.

If this feature doesn't exist, is this something you would be willing to implement?

And if not, would you be open to accepting a PR for it?

**Comment by tobymao** [comment]
i think this is not really trivial because tokens don't map 1 to 1 with ast nodes. you can certainly get line numbers and columns for tokens.

we don't plan to implement this, but we would be happy to discuss an approach and receive/review a well crafted PR. 

happy to discuss further here or on [slack](https://tobikodata.com/slack)
