### ISSUE TITLE
Transpiling postgres extract() to sqlite

### ISSUE THREAD

**Issue by apotheque** [tobymao/sqlglot#2592]
**Description**
I attempted to migrate a set of PostgreSQL queries to SQLite and encountered a problem with the conversion of the PostgreSQL extract() function.

**SQLGlot version**
19.6.0

**Fully reproducible code snippet**
```python
import sqlglot

sqlite_sql = sqlglot.transpile("SELECT * FROM table1 WHERE EXTRACT(year FROM insert_date) = 2023", 'postgres', 'sqlite')[0]
print(sqlite_sql)
```

**Expected Behavior**
SQLite doesn't support extract() function. SQLite analog for extract() is strftime(), so the resulting sql should be like this:
```sql
SELECT * FROM table1 WHERE CAST(strftime('%Y', insert_date) AS INTEGER) = 2023
```
or like this:
```sql
SELECT * FROM table1 WHERE strftime('%Y', insert_date) = '2023'
```

**Actual Behavior**
SQL is left unchanged and fails if executed against SQLite database:
```sql
SELECT * FROM table1 WHERE EXTRACT(year FROM insert_date) = 2023
```

**Official Documentation**
[PostgreSQL extract()](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT)
[SQLite Date And Time Functions](https://www.sqlite.org/lang_datefunc.html)

**Comment by georgesittas** [comment]
Hey @apotheque, I'm not sure if the proposed transpilation is necessarily correct:

Postgres:

```
georgesittas=# select extract(year from cast('2020-06-01' as date));
 extract
---------
    2020
(1 row)
```

SQLite:

```
sqlite> select strftime('%Y', cast(cast('2020-06-01' as date) as integer));
-4707
```

It seems that `strftime` is expecting a string?

```
sqlite> select strftime('%Y', '2020-06-01');
2020
```

However, Postgres' `EXTRACT` fails when I supply a date string instead of a date value:

```
georgesittas=# select extract(year from '2020-06-01');
ERROR:  function pg_catalog.extract(unknown, unknown) is not unique
LINE 1: select extract(year from '2020-06-01');
               ^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
```

In any case, this doesn't seem like high priority for us right now, though we'll be happy to accept a well-crafted PR if you're willing to contribute one. You can also join our [Slack](https://tobikodata.com/slack) if you wanna chat more.

**Comment by joeharris76** [comment]
Reproduced on SQLGlot 30.18.0 and main at `5cfb5997a99010940138670adf3d6b34ac5a0a08` while evaluating BenchBox's SQLite compatibility repairs.

The DATE-cast concern above has changed: current SQLite generation turns `CAST(... AS DATE)` into `DATE(...)`, so this bounded case has a valid SQLite representation:

```python
import sqlite3
import sqlglot

source = "SELECT EXTRACT(YEAR FROM CAST('2020-06-01' AS DATE))"
output = sqlglot.transpile(source, read="postgres", write="sqlite")[0]
print(output)
# SELECT EXTRACT(YEAR FROM DATE('2020-06-01'))

db = sqlite3.connect(":memory:")
print(db.execute("SELECT CAST(STRFTIME('%Y', DATE('2020-06-01')) AS INTEGER)").fetchall())
# [(2020,)]
db.execute(output)
# sqlite3.OperationalError: near "FROM": syntax error
```

Before proposing a generator patch, I want to resolve two cases a blanket integer STRFTIME replacement would mishandle:

1. `EXTRACT(YEAR FROM TIMESTAMP '2020-06-01 12:00:00')`: the timestamp operand currently generates `CAST('2020-06-01 12:00:00' AS TIMESTAMP)`. SQLite applies numeric affinity; wrapping that in STRFTIME yields year **-4707**, not 2020.
2. `EXTRACT(YEAR FROM DATE '2020-06-01') / 3 > 673`: PostgreSQL EXTRACT returns numeric, but lowering it to INTEGER makes SQLite perform integer division and return false. A bare extraction projection would miss that change.

These are SQLite-executed counterexamples on SQLite 3.53.1. The source examples were also executed on DuckDB 1.5.5; PostgreSQL's numeric result type is documented at https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT, not verified against a PostgreSQL server in this run. SQLite's representation rules are at https://www.sqlite.org/lang_datefunc.html.

Would a first contribution scoped to YEAR/MONTH/DAY extraction from DATE values represented as ISO date TEXT be useful, and is there an existing approach you prefer for preserving the source numeric type in surrounding expressions? I would keep timestamp-cast handling, interval extraction, and DuckDB DATE_PART parsing separate rather than bundle them into this fix. Tests would cover DATE casts, columns, nested COALESCE, NULLs, duplicates, leap dates, and the division counterexample.
