### ISSUE TITLE
sqlglot strftime pattern conversion doesn't preserve original text as non-pattern

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2731]
I really like that sqlglot allows specification of `strftime`-style patterns, and allows transpilation of those patterns to the right backend syntax.

However, strings that are **not** backend-specific patterns included in this string get left alone instead of treated as they would be in a call to strftime.

Here's an example going from DuckDB to Postgres:

```
In [5]: import sqlglot as sg

In [6]: sg.parse_one("select strftime('2013-01-02T01:01:01', 'DD %d')", read="duckdb").sql(
   ...:     "postgres"
   ...: )
Out[6]: "SELECT TO_CHAR('2013-01-02T01:01:01', 'DD DD')"
```

When executed, this code results in the string `'02 02'` when it should be `'DD 02'`:

```
ibis_testing=# SELECT TO_CHAR('2013-01-02T01:01:01'::timestamp, 'DD DD');
 to_char
---------
 02 02
(1 row)
```

the solution is to place double quotes around every component of the string that isn't a format specifier:

```
ibis_testing=# SELECT TO_CHAR('2013-01-02T01:01:01'::timestamp, '"DD" DD');
 to_char
---------
 DD 02
(1 row)
```

My example is a bit unrealistic. Something more realistic might look like this:

```
In [1]: import sqlglot as sg

In [2]: sg.parse_one("select strftime('2013-01-02T01:01:01', 'Year: %Y')", read="duckdb").sql(
   ...:     "postgres"
   ...: )
Out[2]: "SELECT TO_CHAR('2013-01-02T01:01:01', 'Year: YYYY')"
```

Running this on postgres the output is incorrect:

```
ibis_testing=# SELECT TO_CHAR('2013-01-02T01:01:01'::timestamp, 'Year: YYYY');
  to_char
------------
 3ear: 2013
(1 row)
```

docs: https://www.postgresql.org/docs/current/functions-formatting.html

specifically this bit:

![image](https://github.com/tobymao/sqlglot/assets/417981/4a05f3b3-c292-49b6-888f-2ee1f7bea9a3)

**Comment by georgesittas** [comment]
@cpcloud this one is a bit involved to solve because of how [format_time](https://github.com/tobymao/sqlglot/blob/main/sqlglot/time.py#L8) works today.

Each dialect has a `TIME_MAPPING` that maps its date/time formats to their equivalent Python `strftime` [formats](https://strftime.org/). In order to make these mappings more compact, we omit identities such as `"%c": "%c"` and rely on `format_time` to reconstruct them by joining equivalent sequences of [single-character chunks](https://github.com/tobymao/sqlglot/blob/main/sqlglot/time.py#L50).

The solution I discussed with Toby is to basically quote all substrings that [don't exist](https://github.com/tobymao/sqlglot/blob/main/sqlglot/time.py#L40) in the corresponding [time tries](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/dialect.py#L98), but that would require us to add the identity mappings _for each dialect_, otherwise we could treat valid formats as string literals and incorrectly quote them.

This is out of scope for us right now, but we'll be happy to implement the fix if you're willing to comprehensively update the time mappings of all dialects in order to include said identities.

**Comment by erickpeirson** [comment]
Interestingly, the behavior has changed here slightly since 2023, as it now appears that parsing with unsupported patterns results in the patterns being left alone as a literal (which is useful)...

```python
sqlglot.parse_one("to_timestamp(x, '%Y%m%d')")
# Anonymous(
#   this=to_timestamp,
#   expressions=[
#     Column(
#       this=Identifier(this=x, quoted=False)),
#     Literal(this='%Y%m%d', is_string=True)])
```

...except when a substring matches a dialect time format, in which case we get mangling. e.g. when parsing with postgres or redshift, `%d` gets mangled to `%%u` inside of `format_time`. 

```python
sqlglot.parse_one("to_timestamp(x, '%Y%m%d')", dialect='redshift')
# StrToTime(
#   this=Column(
#     this=Identifier(this=x, quoted=False)),
#   format=Literal(this='%Y%m%%u', is_string=True))
```

I worked around this by extending the redshift dialect with an empty `TIME_MAPPING`, and overriding function-handlers (e.g. for `TO_TIMESTAMP`) in the base Postgres dialect that weren't parameterized by dialect (and so didn't pick up my extended dialect).
