### ISSUE TITLE
Convert SAMPLE (snowflake) to SAMPLE USING (duckdb)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#2747]
```python
>>> sqlglot.parse_one("""
SELECT * FROM example SAMPLE (3) SEED (82);
            """, read="snowflake").sql(dialect="duckdb")
'SELECT * FROM example SAMPLE (3) REPEATABLE (82)'
```
however [duckdb requires USING SAMPLE](https://duckdb.org/docs/sql/query_syntax/sample), eg:
```
SELECT * FROM example USING SAMPLE (3) REPEATABLE (82)
```

I think this is because the parse tree is different, eg:

Snowflake

```python
>>> sqlglot.parse_one("""
SELECT * FROM example SAMPLE (3) SEED (82);
            """, read="snowflake").find(exp.Select).args["from"].this
(TABLESAMPLE size: 
  (LITERAL this: 3, is_string: False), seed: 
  (LITERAL this: 82, is_string: False), kind: SAMPLE, this: 
  (TABLE this: 
    (IDENTIFIER this: example, quoted: False)))
````                
           
Duckdb
```python
>>> sqlglot.parse_one("""
SELECT * FROM example USING SAMPLE (3) REPEATABLE (82);
            """, read="duckdb").find(exp.Select).args["sample"]
(TABLESAMPLE size: 
  (LITERAL this: 3, is_string: False), seed: 
  (LITERAL this: 82, is_string: False), kind: USING SAMPLE)
```              

Should these be the same parse trees? If not no worries, I'll add a transform instead.

**Comment by georgesittas** [comment]
> Should these be the same parse trees? If not no worries, I'll add a transform instead.

I don't think so, in general samples can either be attached to the Select as a "query modifier" in order to sample the whole resulting relation, or to a table, so you sample only the chosen relation which may be a part of a multi-relation join.

In this case we parse Snowflake's `SAMPLE` in a way that shows that the sampled entity is the table itself, while DuckDB's `USING SAMPLE` applies to the whole relation and so it's parsed as a query modifier. DuckDB also has `TABLESAMPLE` which can be used to sample a single table, see examples at https://duckdb.org/docs/sql/samples.html.
