### ISSUE TITLE
[feat]: sqlglot pre-commit hook

### ISSUE THREAD

**Issue by celoibarros** [tobymao/sqlglot#2892]
Hi there,

Is it possible to create a pre-commit hook with some sqlglot features?

For projects with sql, it would be great to be able to validate before submitting the code.

Best regards.

**Comment by georgesittas** [comment]
Hey, not entirely sure what you mean by "pre-commit hook with some sqlglot features", but sqlglot is [not a SQL validator](https://github.com/tobymao/sqlglot#faq) and so that is probably not what you're looking for? Please use the [discussions](https://github.com/tobymao/sqlglot/discussions) or join our [slack](https://github.com/tobymao/sqlglot#get-in-touch) if you want to chat more about your use case.

**Comment by ashrub-holvi** [comment]
It would be good to have a pre-commit for simple sql autoformatting, you will need to add `.pre-commit-hooks.yaml` and use script defined in `[project.scripts]` inside of config and likely that's it.

**Comment by ashrub-holvi** [comment]
and from the first impression sqlglot is really nice formatter, turned out it's really difficult to find one

**Comment by ashrub-holvi** [comment]
Note: this repo is really heavy, perhaps for pre-commit configuration better to have a separate repo

**Comment by ashrub-holvi** [comment]
Minimalistic example https://github.com/tobymao/sqlglot/pull/6432
