### ISSUE TITLE
For each node add location (start, end) in the original string

### ISSUE THREAD

**Issue by ilyakochik** [tobymao/sqlglot#2947]
**Is your feature request related to a problem? Please describe.**
I want to build SQL linter and want to use SQLGlot to help traverse the tree and find various errors. Once I've found any, I'd like to highlight part of the original code, but for that I'd need `start` and `end` location in the string for the majority of tokens.

**Describe the solution you'd like**
I'd like each of `sqlglot.exp.Expression` to have either an explicitly calculated location `tuple(start: int, end: int)`, or a list of tokens `list[sqlglot.tokens.Token]` that were used to construct an expression.

**Describe alternatives you've considered**
I tried to create `ParserWrapper(sqlglot.parser.Parser)` to intercept calls to `_parse_*()`, or calls to `expression()`, or even keeping track of index changes in `_advance()`. But I was not able to correctly track location or tokens used to construct each instance of `sqlglot.exp.Expression` as for some cases there are more functions involved that change the state of the parser.

**Comment by georgesittas** [comment]
Hey, we've discussed this in the past and decided it's not really in scope for us to implement this right now. The reason is that figuring out the exact range of tokens used to construct a given expression is tricky and I believe we'd also be subscribing to a lot more complexity in the parser since this is an intrusive change, as you've noted in your alternative.
