### ISSUE TITLE
Bigquery lineage broken when using UDF returns

### ISSUE THREAD

**Issue by razvan-am** [tobymao/sqlglot#3047]
Not sure if this is a bug or a feature request, 

Whenever we are using a UDF in Bigquery (non table function) that returns a struct, the lineage fails to compute. 
E.g. a [Javascript UDF](https://cloud.google.com/bigquery/docs/user-defined-functions#javascript-udf-structure)
```sql
CREATE OR REPLACE FUNCTION
  `project_id.dataset_id.P_FN_Charge`(input STRING)
  RETURNS STRUCT<data STRING,
  created_at  STRING>
  LANGUAGE js AS R"""
return JSON.parse(input);
""";
```

**Fully reproducible code snippet**

```python 
test_fn_str = """
select `project_id.dataset_id.P_FN_Charge`(data).*

from `project_id.dataset_id.P_TD_Charge`

"""

schema_dict = {
        'am-project_id': {
            'dataset_id': {
                'P_TD_Charge': {
                    'data': 'string'
                }
            }
        }
    }

parsed_objects = sqlglot.parse(test_fn_str, dialect='bigquery')

print(parsed_objects)
from sqlglot.lineage import lineage
ln = lineage('created_at', test_fn_str, schema=schema_dict,dialect='bigquery')

print(ln)
```

**Error message**
```
line 192, in to_node
    subquery_scope = subquery_scopes[id(subquery)]
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 4317600512
```

**Possible implementation**

What i've tried is to get the return data struct as a schema of the UDF:
```python
schema_dict = {
        'am-project_id': {
            'dataset_id': {
                'P_TD_Charge': {
                    'data': 'string'
                },
                'P_FN_Charge': {
                    'data': 'string',
                    'created_at': 'timestamp'
                }
            }
        }
    }
```

**Comment by georgesittas** [comment]
Hey, thanks for the report.

The UDF support is not great at the moment, but we plan to improve it once we find some bandwidth. Basically, the optimizer needs to be adjusted to recognize UDFs and qualify them properly, otherwise this won't work.

 By the way, I think your schema is incorrect. You're using `am-project_id` for the project name but in your query you have `project_id` - I would expect `{"project_id": ...}`. Is that intentional, and if so why?

I've noticed a couple of things that can be improved short-term, such as avoiding throwing a `KeyError` here, but the solution to the core issue will probably come later, so I'll go ahead and close this as not planned.

cc @tobymao

**Comment by razvan-am** [comment]
Hi @georgesittas , 
Thanks for noticing, 
It was an edit mistake. Our projects start with am and I forgot to remove it there.
