### ISSUE TITLE
TO_NUMBER(number)  is parsed wrongly from oracle to doris

### ISSUE THREAD

**Issue by yx-keith** [tobymao/sqlglot#3093]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
import sqlglot
sql="""
SELECT to_number(x) from tmp;
"""
sqlglot.transpile(sql,read="oracle", write="doris")[0]
```
output is below:
`SELECT to_number(x) from tmp;`
oracle has to_number function,but doris don't have it.I think it should be converted to cast(x as double)

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by georgesittas** [comment]
This is a bit more nuanced than just simply converting `TO_NUMBER` into a cast at parse time, because there are more arguments involved and you need to preserve them. It's not high priority for us so it's out of scope right now, but feel free to make a PR if you need it. I'd suggest looking at how `TO_CHAR` is handled first.
