### ISSUE TITLE
hyphens not recognised as part of table names

### ISSUE THREAD

**Issue by smeyn** [tobymao/sqlglot#316]
```
SELECT * from  
ecc-timezoneoffset
```
will raise a parse error with `parse_one(sql,read="bigquery")`
`ParseError: Invalid expression / Unexpected token. Line 2, Col: 4`
quoting the table name with back ticks works.

However the above is valid BigQuery sql

**Comment by tobymao** [comment]
@smeyn i understand that this may work in bigquery but it's pretty non-standard and it's best practice to name your tables without special characters.

it's very hacky to support this because the minus sign is used for subtraction, i don't know any other sql language that supports this and so i'm not inclined to add support for it.

i apologize, but your best option for now is to wrap tables like this in double quotes.

**Comment by tobymao** [comment]
fyi this works now

**Comment by smeyn** [comment]
Thanks. Very useful
