### ISSUE TITLE
add line numbers for parsed SQL nodes 

### ISSUE THREAD

**Issue by smeyn** [tobymao/sqlglot#3173]
I am trying to write a code improver for SQL to catch common problems. The improver would output suggestions for specific parts of SQL. For that I'd love to be able to add the line number of the parsed SQL statement. 

Have `sqlglot.parse` and `sqlglot.parse_one` add line numbers to the meta data of expressions

**Describe alternatives you've considered**
at the moment i create the existing SQL snippet (via the `.sql` property) along side the improved snippet. But for longer SQL statements users may find it frustrating, esp as the generated SQL snippet may have different line formatting

**Comment by smeyn** [comment]
This is comparable to Pylint, where the AST contains this information to allow custom checkers specify the exact location of the snippet's frame in the source code

**Comment by tobymao** [comment]
this can't really be done because our ast doesn't map to the sql query directly. line information is stored in tokens and is available while parsing, but after the fact, we don't store them.

there are currently no plans to add this information as it wouldn't be feasible to maintain.

happy to chat about this more.
