### ISSUE TITLE
Propagate tokens for every expression in the tree

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3174]
We'd like to access token information while traversing the AST. What is the level of effort here?

See
- https://github.com/tobymao/sqlglot/issues/3159#issuecomment-2003811697

**Comment by nfx** [comment]
cc @tobymao

**Comment by georgesittas** [comment]
Hi @nfx,

As I explained, this is out of scope for us right now. The level of effort is most certainly high because expression parsing usually spans several methods and you don't always have access to the first token. We're also not willing to subscribe to additional complexity that does not scale well, such as manually adding a token to every expression constructed ever.

You can reach out in [Slack](https://tobikodata.com/slack) if you're planning to work on it, thanks.

See also:
- https://github.com/tobymao/sqlglot/issues/3173
- https://github.com/tobymao/sqlglot/issues/2580
- https://github.com/tobymao/sqlglot/issues/2947, etc.
