### ISSUE TITLE
ClickHouse: fail to qualify "WITH <expression> AS <identifier>"

### ISSUE THREAD

**Issue by herry13** [tobymao/sqlglot#3197]
**Before you file an issue**
- Check if the issue still exists on main --> Yes, it still exists in main.

**Fully reproducible code snippet**

```sql
import sqlglot
from sqlglot.optimizer.qualify import qualify
from sqlglot.dialects.clickhouse import ClickHouse

dialect = ClickHouse()
query = "with toDate('2024-03-20') AS mydate SELECT mydate"
statement = sqlglot.maybe_parse(query, dialect=dialect, error_level=sqlglot.ErrorLevel.RAISE)
qualify(statement, dialect=dialect)
```

**Official Documentation**

[Example on using WITH syntax](https://clickhouse.com/docs/en/sql-reference/statements/select/with#examples) on ClickHouse documentation website.

**Comment by herry13** [comment]
This is related to #3175. The previous bug report is about parsing (line `maybe_parse`), not qualifying.

**Comment by georgesittas** [comment]
I wonder, does ClickHouse simply replace all instances of `mydate` in the query that follows the `WITH` definition? Perhaps this expansion could happen before hitting the qualifier.

The reason this fails is because it hasn't been a priority for us to take this special CTE AST case into account, since it's very ClickHouse specific. My guess is that we shouldn't pollute the optimizer code around CTEs to take this into account, but should instead preprocess the AST first to canonicalize it into something we can deal with.

**Comment by herry13** [comment]
> does ClickHouse simply replace all instances of mydate in the query that follows the WITH definition?

I believe this is correct if `<expression>` is a column expression.

If it is a `select ...` then the possible routes are:
1. if the select's result is 1 row and 1 column (scalar value) (e.g. `with (select col from db.table limit 1) as result select result;`), then it behaves the same as the column expression where all instances are replaced;
2. if the select's result is 1 row and multiple columns, then all column values are merged as a tuple, then all instances are replaced with this tuple (e.g. `with (select * from db.table limit 1) as result select result;`);
3. if the select's result is multiple rows (e.g. `with (select * from db.table limit 2) as result select result;`), regardless the number of columns, then it raises an error: `Code: 125. DB::Exception: Scalar subquery returned more than one row`.

The above use cases are based on my observation running the example queries directly on clickhouse.

**Comment by georgesittas** [comment]
I see, thanks for clarifying, we'll take a look soon.

**Comment by georgesittas** [comment]
Hey @herry13, I think I'll close this one after, at least for now. It doesn't seem trivial and since it's not a very high priority item for us, I'd like to avoid introducing a new transformation in the optimizer just to deal with this special case.

In general, it's very tricky to fully support ClickHouse, especially in the optimizer, as they have various [non-standard SQL extensions](https://github.com/ClickHouse/ClickHouse/issues/23194) not supported by other dialects.

We'll be happy to accept PRs. If you're interested to work on this, please reach out in [Slack](https://tobikodata.com/slack) to discuss the implementation details.

**Comment by herry13** [comment]
@georgesittas I understood the reason.

Is there a chance for you to review and merge a PR that resolves a case where the "<expression>" is a column expression? I think we can implement your suggestion to replace all instances after "WITH". If the answer is yes, then I'll find some time to implement it.

What do you think?
