### ISSUE TITLE
Timestamp trunc method issue from postgres to MySQL

### ISSUE THREAD

**Issue by sivpr2000** [tobymao/sqlglot#3366]
I was trying to convert an SQL query from Postgres to MySQL. Check the following code snippet

```
import sqlglot
sqlglot.transpile("SELECT date_trunc('hour', timestamp '2001-02-16 20:38:40') FROM dual", read="postgres", write="mysql") 
```

This returns

`["SELECT TIMESTAMP_TRUNC(CAST('2001-02-16 20:38:40' AS DATETIME), HOUR) FROM dual"]`

But MySQL doesn't have TIMESTAMP_TRUNC method. Please look into this.

**Comment by georgesittas** [comment]
What's the issue @FaizelK?

**Comment by FaizelK** [comment]
epoch is not a thing in mysql, i wanted to convert that query to mysql, but it still kept epoch. when running this my mysql here are the results because  MySQL does not support the EXTRACT(epoch FROM :

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'epoch FROM (CAST(mt.cross_time AS DATETIME) - CAST(mt.second_cross_time AS DATET' at line 1`

**Comment by VaggelisD** [comment]
Hi @FaizelK, can you please open a separate issue describing the faulty behavior? Please include a minimum reproducible example, what you would ideally want to transpile to as well as any docs validating that.

Thanks!

**Comment by FaizelK** [comment]
@VaggelisD 
I have done so, Please see new issue and suggestions
