### ISSUE TITLE
expression.AlterTable doesn't seem to support dropping columns

### ISSUE THREAD

**Issue by ikasovitch** [tobymao/sqlglot#3442]
**Fully reproducible code snippet**
```
from sqlglot import parse_one, diff 
from sqlglot.diff import Insert, Remove
import sqlglot.expressions as exp

source_sql = """
CREATE TABLE IF NOT EXISTS a(
a_id                   uuid               NOT NULL,
a_test                 int                NOT NULL,
CONSTRAINT pk_a PRIMARY KEY (a_id)
);
"""

target_sql = """
CREATE TABLE IF NOT EXISTS a(
a_id                   uuid               NOT NULL,
a_name                 text               NOT NULL,
a_email                text               NOT NULL,
CONSTRAINT pk_a PRIMARY KEY (a_id)
);
"""

source_expr = parse_one(source_sql, dialect="postgres")
target_expr = parse_one(target_sql, dialect="postgres")

diffs = diff(source_expr, target_expr)

for e in diffs:
    if isinstance(e, (Insert, Remove)) and e.expression.find(exp.ColumnDef):
        print(f"{exp.AlterTable(this=e.expression.parent.this, actions=[e.expression])}")


# Actual output
# ALTER TABLE a ADD COLUMN a_test INT NOT NULL
# ALTER TABLE a ADD COLUMN a_name TEXT NOT NULL
# ALTER TABLE a ADD COLUMN a_email TEXT NOT NULL

# Expected output
# ALTER TABLE a DROP COLUMN a_test
# ALTER TABLE a ADD COLUMN a_name TEXT NOT NULL
# ALTER TABLE a ADD COLUMN a_email TEXT NOT NULL
```

Suspicious area:
https://github.com/tobymao/sqlglot/blob/5cfb29c7ff6015e39d7fd5b94ed2aa66436e33ae/sqlglot/generator.py#L2997C9-L2997C23
`ColumnDef` always prints `ADD COLUMN` even when the diff result type is a `Remove`.

**Comment by georgesittas** [comment]
This is expected behavior. The reason you're seeing these outputs is because you're not constructing the AST correctly. The `diff` module doesn't produce `ALTER` statements based on the `Insert`s or `Remove`s in the edit script, so using `e.expression` doesn't really make sense in this context. You'll need to manually construct the correct `AlterTable` nodes based on the edit script actions; SQLGlot doesn't provide a way to do this automatically.

See https://github.com/tobymao/sqlglot/blob/main/posts/sql_diff.md

**Comment by slevy** [comment]
Thanks for the fast reply. I'm working with [ikasovitch](https://github.com/ikasovitch) on this.
It seems that SQLGlot provides implementations for at least the following cases: ```add_column_sql()```, ```droppartition_sql()``` and ```addconstraint_sql()```.  Why were these use-cases chosen?  If for example ```drop_column_sql()``` does not exists, how can we provide that action to ```AlterTable```?

Thanks.

**Comment by georgesittas** [comment]
The `DROP COLUMN` syntax is supported:

```python
>>> import sqlglot
>>> sqlglot.parse_one("ALTER TABLE integers DROP COLUMN k")
AlterTable(
  this=Table(
    this=Identifier(this=integers, quoted=False)),
  actions=[
    Drop(
      this=Table(
        this=Identifier(this=k, quoted=False)),
      kind=COLUMN)])
>>> sqlglot.parse_one("ALTER TABLE integers DROP COLUMN k").sql()
'ALTER TABLE integers DROP COLUMN k'
```

You can use the parser as the source of truth for what is and isn't supported, and figure out what expressions you need to construct from that. You'll need to have an understanding of both the AST and the parser / generator modules in order to do more advanced stuff, so I'd suggest you study the code a bit and also look at the diff and [AST primer](https://github.com/tobymao/sqlglot/blob/main/posts/ast_primer.md) posts.

> Why were these use-cases chosen?

Syntax is supported on an on-demand basis, as there are countless statements in the supported SQL dialects. We don't necessarily plan to prioritize adding new syntax for the `ALTER` statement right now, but well-crafted & tested PRs are welcome.

**Comment by slevy** [comment]
Understood. Thank you!
