### ISSUE TITLE
Rendering of `TABLESAMPLE` yields invalid `PERCENT` keyword for Postgres dialect

### ISSUE THREAD

**Issue by whummer** [tobymao/sqlglot#3456]
Hi folks, 

big kudos for the quick turnaround on some of the issues I've recently filed, really appreciated! 🙌 🚀 

Looks like we've just hit have another small one - related to rendering of `TABLESAMPLE` percentages for Postgres as target.

Given the following code:
```
query = "SELECT * FROM test AS _tmp TABLESAMPLE (5)"
result = parse_one(query, read="snowflake").sql(dialect="postgres")
print(result)
```

... `sqlglot` generates:
```
SELECT * FROM test AS _tmp TABLESAMPLE (5 PERCENT)
```

... however, this is not valid Postgres syntax, as Postgres:
* (1) requires the `SYSTEM` keyword to be present as default, and 
* (2) does not recognize the `PERCENT` keyword. 

So, the correct syntax in Postgres would be:
```
SELECT * FROM test AS _tmp TABLESAMPLE SYSTEM (5)
```

For point (2), we've been able to use the following workaround in our code base:
```
    Postgres.TABLESAMPLE_SIZE_IS_PERCENT = True
```

We also have a workaround for point (1) in place, so not a blocker, but would be great if it could be fixed for the Postgres dialect as well. 🙌

**Comment by georgesittas** [comment]
@whummer appreciate the reports, PRs would also be welcome for future issues you come across.

**Comment by georgesittas** [comment]
> (1) requires the SYSTEM keyword to be present as default, and

FYI I don't think this is 100% correct. Postgres requires either `BERNOULLI` or `SYSTEM` to be used, but doesn't specify a default value, which is why there's a syntax error if the method is omitted. Snowflake on the other hand uses `BERNOULLI` as a default, so for the transpilation to be correct I made it so that we'll generate `BERNOULLI` for your example when targeting Postgres.
