### ISSUE TITLE
[bug] These conversions are consistent, but not consistent in meaning ， from pg to mysql

### ISSUE THREAD

**Issue by Toms1999** [tobymao/sqlglot#3501]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by Toms1999** [comment]
one:
`select 1
from edw_dws.dws_loan_due_date_push_detail_v2
where confirm_date <= date(now() + '-21 days');`

**Comment by georgesittas** [comment]
@Toms1999 I'm going to close these tickets as not planned.

Reviewing, reproducing and fixing issues is time-consuming and we're a small team, so we kindly ask that you put more effort into future reports. This means:

- Not ignoring the issue template in favor of making followup replies in the thread.
- Clearly specifying what the input/output dialects are
- Explain why the actual behavior is different from the expected, providing examples and documentation as needed.
- Formatting the code appropriately so it's easy to parse.
- Ideally, reducing the examples so that they're minimally reproducible, i.e. they don't contain irrelevant information.
