### ISSUE TITLE
Snowflake Parser fails on columns called `case`

### ISSUE THREAD

**Issue by kosta-foundational** [tobymao/sqlglot#3648]
Fully reproducible code snippet

```
    query = """
SELECT
    source.case
 FROM source
"""
sqlglot.parse(query, sqlglot.Dialects.SNOWFLAKE)
```
``
This snippet raises an exception: sqlglot.errors.ParseError: Expected END after CASE.
However, it does compile in SNOWFLAKE, and SNOWFLAKE does allow columns with this name.

**Comment by VaggelisD** [comment]
Hey @kosta-foundational,

Thanks for reporting this issue. I did some digging and decided that it's out of scope for SQLGlot now as differentiating between `CASE WHEN` and your case hides a lot of ambiguity across dialects.

The best practice in overcoming this issue is to quote the reserved keywords in order for SQLGlot to pick them up as identifiers instead of attempting to parse them as SQL constructs.

**Comment by kosta-foundational** [comment]
> Hey @kosta-foundational,
> 
> Thanks for reporting this issue. I did some digging and decided that it's out of scope for SQLGlot now as differentiating between `CASE WHEN` and your case hides a lot of ambiguity across dialects.
> 
> The best practice in overcoming this issue is to quote the reserved keywords in order for SQLGlot to pick them up as identifiers instead of attempting to parse them as SQL constructs.

@VaggelisD , thank you for the fast response and for the honest communication of your considerations.
