### ISSUE TITLE
Sqlglot does not preserve new Databricks's Variant Syntax

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#3673]
The newest Databricks Runtime (15.3) does support a number of fancy syntax for their new Variant Type.
Docs: https://docs.databricks.com/en/semi-structured/variant.html

Those do not get preserved

```python
import sqlglot as sg
print(sg.parse_one("SELECT raw:store.bicycle FROM store_data", dialect="databricks").sql("databricks"))
-- prints "SELECT GET_JSON_OBJECT(raw, '$.store.bicycle') FROM store_data"

print(sg.parse_one("SELECT raw:`zip code`, raw:`fb:testid` FROM store_data", dialect="databricks").sql("databricks"))
-- prints "SELECT GET_JSON_OBJECT(raw, '$[\\'`zip\\'][\\'code`\\']'), GET_JSON_OBJECT(raw, '$[\\'`fb\\'][\\'testid`\\']') FROM store_data"
```

**Comment by georgesittas** [comment]
This is intentional, so unless there's an issue with the semantics of the resulting queries, changing it is out of scope. Happy to continue discussing.

**Comment by georgesittas** [comment]
I see, thanks for clarifying. We'll take a closer look 👍

**Comment by georgesittas** [comment]
Transpilation of `:` will get a bit tricky now, because it requires type information.. @VaggelisD maybe let's try to change the `-> databricks` generation so that it preserves the `:` operator but continue parsing it into a `JSONExtract` to preserve current behavior and do a best-effort transpilation as if it was a JSON extraction.
