### ISSUE TITLE
Incorrect type cast in conversion from Spark to Presto in timestampad function

### ISSUE THREAD

**Issue by ddelzell** [tobymao/sqlglot#3778]
I have the following line in my SELECT statement, (consider the second argument in the `timestampadd` Spark function)...

```
q = "select region_uuid, 
    timestampadd(minute, floor(extract(minute from delivery_created_time_local)/30)*30, date_trunc(‘hour’, time_org)) as time 
    from timeseries"
sqlglot.transpile(q, read='spark', write='presto')
```
The Presto transpiled result is

```
SELECT region_uuid, 
    DATE_ADD('MINUTE', FLOOR(CAST(EXTRACT(MINUTE FROM delivery_created_time_local) AS DOUBLE) / NULLIF(30, 0)) * 30, DATE_TRUNC('‘HOUR’', time_org)) AS time 
FROM timeseries
```

However, DATE_ADD requires the second argument to be BIGINT, not DOUBLE, as it's currently being cast.

**Comment by VaggelisD** [comment]
Hey @ddelzell, thanks for reporting this once again. The reason this cast is there is to match Spark's division semantics but the `DOUBLE` type bubbles up to `DATE_ADD` because `FLOOR()` (among other math functions) is type-dependent on Presto/Trino.

I have the fix ready but will potentially require a non-trivial change in our type inference logic.

**Comment by ddelzell** [comment]
Thanks so much for looking into this.
