### ISSUE TITLE
[databricks] `OPTIMIZE gold_user_journey ZORDER BY uid` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3826]
```
def test_x():
    import sqlglot
    q = "OPTIMIZE gold_user_journey ZORDER BY uid"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> WARN [sqlglot] 'OPTIMIZE gold_user_journey ZORDER BY uid' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/delta-optimize.html

**Comment by georgesittas** [comment]
These warnings aren't indicating there's an error, but rather that sqlglot doesn't currently support said syntax. In many cases that's intentional because either 1) it's not high ROI / necessarily meaningful to parse the clause into a non-`Command` AST or 2) it requires a big effort and it's not a high priority for us to put that effort.

This one in particular is low priority, so closing it as not planned. We'd appreciate it if you started contributing PRs for these tickets.
