### ISSUE TITLE
transpile from snowflake to duckdb with convert timezone is not working

### ISSUE THREAD

**Issue by milonimrod** [tobymao/sqlglot#3875]
**Fully reproducible code snippet**

The following snowflake query is transpile into a duckdb and fails
```
SELECT date_trunc('month', CONVERT_TIMEZONE('UTC', 'Europe/Berlin', anchor_hour)) AS ANCHOR,
                   SUM(sum_paid_usd) AS SUM_PAID,
                   SUM(CASE WHEN anchor_hour > current_timestamp() THEN sum_due_not_paid ELSE 0 END) AS SUM_UPCOMING,
                   SUM(CASE WHEN anchor_hour < current_timestamp() THEN sum_due_not_paid ELSE 0 END) AS SUM_OVERDUE,
                   SUM(count_paid_through_hb_usd) AS COUNT_PAID,
                   SUM(CASE WHEN anchor_hour > current_timestamp() THEN count_due_not_paid ELSE 0 END) AS COUNT_UPCOMING,
                   SUM(CASE WHEN anchor_hour < current_timestamp() THEN count_due_not_paid ELSE 0 END) AS COUNT_OVERDUE,
            FROM pdt_mongo_payment_reporting_aggregated
            WHERE company_id = '1111' AND anchor_hour BETWEEN '2023-12-31 23:00:00+00:00' AND '2024-07-31 21:59:59.999000+00:00'
            GROUP BY 1
            ORDER BY 1 ASC;
```

python code `transpile(raw, read="snowflake", write="duckdb", pretty=True)[0]`

Output query:
```
SELECT
  DATE_TRUNC('MONTH', CONVERT_TIMEZONE('UTC', 'Europe/Berlin', anchor_hour)) AS ANCHOR,
  SUM(sum_paid_usd) AS SUM_PAID,
  SUM(CASE WHEN anchor_hour > CURRENT_TIMESTAMP THEN sum_due_not_paid ELSE 0 END) AS SUM_UPCOMING,
  SUM(CASE WHEN anchor_hour < CURRENT_TIMESTAMP THEN sum_due_not_paid ELSE 0 END) AS SUM_OVERDUE,
  SUM(count_paid_through_hb_usd) AS COUNT_PAID,
  SUM(CASE WHEN anchor_hour > CURRENT_TIMESTAMP THEN count_due_not_paid ELSE 0 END) AS COUNT_UPCOMING,
  SUM(CASE WHEN anchor_hour < CURRENT_TIMESTAMP THEN count_due_not_paid ELSE 0 END) AS COUNT_OVERDUE
FROM pdt_mongo_payment_reporting_aggregated
WHERE
  company_id = '1111'
  AND anchor_hour BETWEEN '2023-12-31 23:00:00+00:00' AND '2024-07-31 21:59:59.999000+00:00'
GROUP BY
  1
ORDER BY
  1 ASC```

The `CONVERT_TIMEZONE` is not correct. fixing it to `timezone('Europe/Berlin', anchor_hour)` solves the issue. I believe that the issue is that we are converting from specific TZ to another TZ but I'm not sure.

**Comment by VaggelisD** [comment]
Hey @milonimrod,

Thanks for reporting this. From what I see, in Snowflake `CONVERT_TIMEZONE` has two versions depending on the parameter count, with the 3-arg version being `CONVERT_TIMEZONE(source_tz, target_tz, timestamp_ntz)`; This means that Snowflake can take a `TIMESTAMP` without timezone information and transform it to `target_tz` as if it was originally in `source_tz`.

DuckDB also has two versions of `TIMEZONE(text, timestamp / timestamp_tz)`, but the version that accepts a timestamp **without** timezone information will convert it to the `target_tz` as if it was originally in GMT. Your solution works because you used `UTC`, but if the `source_tz` was different there'd be a difference in results afaict.

I've not been able to find a complete Snowflake -> DuckDB transpilation for it yet but hopefully it can be pieced together.

**Comment by georgesittas** [comment]
Hi @milonimrod,

I'm trying to understand how we can transform the 3-arg variant in Snowflake. DuckDB doesn't have a similar function where you can specify the source timezone, i.e. what timezone the input timestamp's in. It seems like in your example you omitted `'UTC'` altogether, but I'm not sure if this is correct. Is `anchor_hour` already a timestamp with UTC time zone, i.e. has type `TIMESTAMPTZ`? If not, DuckDB's [docs](https://duckdb.org/docs/sql/functions/timestamptz.html#timezonetext-timestamp) indicate that it will be interpreted in local time.

The 3-arg variant is not being transpiled intentionally because other dialects don't support this concept IIRC. I'm leaning towards closing this as not planned for now, but feel free to share ideas and I'll take another look later.

**Comment by milonimrod** [comment]
Hi, thank you for the quick response. Is there a way to create the mapping in duckDB by running the 3 args version as two nested calls?

The first will be to convert FROM tz1 to UTC and the second call from UTC TO tz2.
 Is this an option?

**Comment by VaggelisD** [comment]
@milonimrod  Hmm, I think it can be done through nested `TIMEZONE()` calls without having to go through UTC actually:

`SELECT TIMEZONE(target_tz, TIMEZONE(source_tz, ts::TIMESTAMP))`

This should have the same results and it's also safe because Snowflake accepts only TIMESTAMP_NTZ in the 3-arg version afaict. I'll give it some more thought and will upload a PR later in the day if it's g2g.

**Comment by milonimrod** [comment]
Hi @VaggelisD,
I can confirm that is is working as expected.
`SELECT TIMEZONE('America/Los_Angeles', TIMEZONE('Asia/Jerusalem', anchor_hour::TIMESTAMP)) AS pass, anchor_hour from read_parquet('/tmp/snowflake/output_qw2w2w_14/*.parquet', filename = true) limit 100;`

The output is as expected:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/f7f1bcb0-6a57-4079-a4a3-54f6e47e3e2f">
