### ISSUE TITLE
Error in parsing of `JOIN ... USING` expressions in Snowflake

### ISSUE THREAD

**Issue by dlahyani** [tobymao/sqlglot#3881]
In Snowflake (maybe in other dialects too), it is valid to specify the column name in `USING` expression  as `TABLE.COL_NAME` (in addition to the more commonly used format of `USING COL_NAME` without specifying a table).

For example, the following query is syntactically valid in Snowflake:
```sql
SELECT * 
FROM T1 
LEFT JOIN T2 USING(T1.a)
```

When trying to parse such query with sqlglot an exception is raised:
```
sqlglot.errors.ParseError: Expecting ). Line 3, Col: 22.
  SELECT * FROM T1 LEFT JOIN T2 USING(T1.a)
```

**Fully reproducible code snippet**
```python
sqlglot.parse(
    sql="""
        SELECT * 
        FROM T1 
        LEFT JOIN T2 USING(T1.a)
    """, 
    dialect=sqlglot.Dialects.SNOWFLAKE)
```

**Official Documentation**
https://docs.snowflake.com/en/sql-reference/constructs/join

**Comment by tobymao** [comment]
i don't see this in the documentation

```
USING( <column_list> )

    A list of columns in common between the two tables being joined; these columns are used as the join columns. The columns must have the same name and meaning in each of the tables being joined.

    For example, suppose that the SQL statement contains:
```

**Comment by dlahyani** [comment]
Hi @tobymao.
You are right, this is indeed not mentioned in the documentation but:
a. Nothing in the docs says that it is not a valid syntax.
b. De-facto it works and people (a few customers) have queries like this.

I don't know if it makes any difference.

**Comment by georgesittas** [comment]
FWIW this is invalid in every other engine I tested (most of what sqlglot supports), they treat `USING (t.c)` as a syntax error, which makes sense. I'm assuming the tables aren't functionally important in this context and can just be dropped, since they don't document this.

Imho I don't really feel like this is worth supporting, because it's bad/unconventional SQL that's mostly unsupported, but I went ahead and opened a [PR](https://github.com/tobymao/sqlglot/pull/3885) with a fix and we can decide later if it's worth merging, cc @tobymao.

**Comment by dlahyani** [comment]
Thank you @georgesittas and @tobymao for the quick fix. I appreciate your extra effort here.

I agree this is an odd usage of the `USING` statement and from my experiments it does not make any difference if omitted. Sadly without this we fail to properly parse few queries of our customers.
