### ISSUE TITLE
ORACLE : Column name in group by replaced by the column number when an alias with the same name as the column is used

### ISSUE THREAD

**Issue by Hal-H2Apps** [tobymao/sqlglot#3933]
SQLGlot Version: 25.14.1dev1 
**Fully reproducible code snippet**
```python
import sqlglot
sql = sqlglot.parse_one(sql='SELECT MIN(Col1), Col2 AS Col2 FROM Test GROUP BY Col2', read='oracle')
print(sql.sql(dialect='oracle'))
```
_Returns a bad query:_
--> SELECT MIN(Col1), Col2 AS Col2 FROM Test GROUP BY 2

The GROUP BY shouldn't be on the column's number but on the column's name 

```python
import sqlglot
sql = sqlglot.parse_one(sql='SELECT MIN(Col1), Col2 FROM Test GROUP BY Col2', read='oracle')
print(sql.sql(dialect='oracle'))
```
_Returns a correct query:_
--> SELECT MIN(Col1), Col2 FROM Test GROUP BY Col2

We can notice that the following returning query is correct :
```python
import sqlglot
sql = sql = sqlglot.parse_one(sql='SELECT MIN(Col1), Col2 AS Col3 FROM Test GROUP BY Col2', read='oracle')
print(sql.sql(dialect='oracle'))
```
_Returns a correct query:_
--> SELECT MIN(Col1), Col2 AS Col3 FROM Test GROUP BY Col2

The problem only occurs when the alias of the column is the column name (I know there is now reason to put an alias in this case, but I'm sadly not the developer of the query).

**Official Documentation**
https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj32654.html

**Comment by georgesittas** [comment]
There was a similar [issue](https://github.com/tobymao/sqlglot/issues/3803) recently and we decided that it's out of scope to remove this transformation since positional references in `GROUP BY` are supported after Oracle 23.

If you're working with an older version of Oracle and don't want this transformation, you could subclass or patch the `Oracle` dialect to remove `exp.Group` from `Oracle.Generator.TRANSFORMS`.

Closing this as not planned, can reopen if I've missed something.
