### ISSUE TITLE
Transpile Oracle nvl function to ClickHouse ifNull

### ISSUE THREAD

**Issue by sleshJdev** [tobymao/sqlglot#3952]
**Fully reproducible code snippet**
```
from sqlglot.dialects import Oracle, ClickHouse
sqlglot.transpile("select nvl(null, 1)", read=Oracle, write=ClickHouse, comments=False)
['SELECT nvl(NULL, 1)']
```
expected result `SELECT ifNull(NULL, 1)`

**Comment by VaggelisD** [comment]
Hey @sleshJdev, thanks for reporting this.

Is there any tangible difference between Clickhouse's `Coalesce` and `ifNull`, besides the number of args? 

The transpilation is not working because of an Oracle issue which I've fixed, but note that the Clickhouse result after my PR would be `SELECT COALESCE(NULL, 1)`. 

Across all dialects (except Oracle afaik) `ifNull` / `NVL` functions are a "subset" of `COALESCE`; The Clickhouse docs don't mention any subtle differences, so if we don't have to explicitly map Oracle's `NVL` to CH's `ifNull` that will further simplify things.

**Comment by sleshJdev** [comment]
Agree. COALESCE is way to go. Let's do it this way
