### ISSUE TITLE
Issue with element_at translation from spark to duckdb

### ISSUE THREAD

**Issue by dor-bernstein** [tobymao/sqlglot#4025]
ELEMENT_AT is a registered function in both duckdb and spark sql. However, in spark it is used the get the element at index n from an array and in duckdb, it is used on maps to get the item at a specific key. The relevant function in duck db is list_extract.

**Fully reproducible code snippet**
```python
from sqlglot import parse_one
query = "SELECT element_at(arr, 1) as elem from table"
parse_one(query, dialect="spark").sql(dialect="duckdb")
```

The output is: SELECT ELEMENT_AT(arr, 1) AS elem FROM "table".
while it should be SELECT LIST_EXTRACT(arr, 1) AS elem FROM "table" 

**Official Documentation**
1. Spark docs: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.element_at.html
2. DuckDB element at: https://duckdb.org/docs/sql/functions/map#element_atmap-key
3. DuckDB List Extract: https://duckdb.org/docs/sql/functions/list#list_extractlist-index

Thanks a lot!

**Comment by georgesittas** [comment]
This isn't trivial to solve because `ELEMENT_AT` is also used to extract values from maps in Spark, so you can't safely transpile `ELEMENT_AT(x, value)` to `LIST_EXTRACT` without having type information. A best-affort approach that leverage `annotate_types` would be possible, but it's not a high priority for us right now - well-tested PRs are welcome.
