### ISSUE TITLE
A quoted column in ORDER BY was enclosed in double quotes again

### ISSUE THREAD

**Issue by EugeneTorap** [tobymao/sqlglot#4057]
Hey! I found an issue when a quoted column in ORDER BY was enclosed in double quotes again

```python
col1 = 'aaa.col1'
col2 = 'aaa."col2"'

ordered1 = exp.Ordered(this=exp.column(col1, quoted=False), desc=False)
ordered2 = exp.Ordered(this=exp.column(col2, quoted=False), desc=False)

print(ordered1.sql(dialect=Dialects.CLICKHOUSE))
print(ordered2.sql(dialect=Dialects.CLICKHOUSE))
```

We got the such output:
```
aaa.col1 ASC
aaa.""col2"" ASC
```

But I expect  `aaa."col2" ASC`

**Comment by georgesittas** [comment]
I think this behavior is intentional, you need to use `exp.to_column(...)` instead:

```python
>>> from sqlglot import exp
>>> exp.to_column('"foo"').sql()
'"foo"'
```

**Comment by EugeneTorap** [comment]
@georgesittas It's just the simple example. In my practice I parse a large SQL `parse_one(sql, read=Dialects.CLICKHOUSE)` then I want to add ORDER BY to this SQL and convert to SQL string again. In this situation I have `aaa.""col2"" ASC` in the large SQL

**Comment by georgesittas** [comment]
Yep, that's expected; `exp.column` is not supposed to be used like that, because it constructs an incorrect AST. The `quoted` argument is actually propaged to `to_identifier`, and basically allows you to add or switch off quotes completely for some identifiers that we'd automatically quote (i.e. when they're "unsafe").

If your columns are already quoted and represented as strings, you'll need to use `to_column` like I showed above.
