### ISSUE TITLE
[hive] Date addition and subtraction parsing error

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#4149]
> sql = "select (cast('2000-08-19' as date) + 14 days)"
ast = parse_one(sql, read="hive")
[Select(
  expressions=[
    Paren(
      this=Alias(
        this=Add(
          this=TryCast(
            this=Literal(this=2000-08-19, is_string=True),
            to=DataType(this=Type.DATE, nested=False)),
          expression=Literal(this=14, is_string=False)),
        alias=Identifier(this=days, quoted=False)))])]

<img width="519" alt="image" src="https://github.com/user-attachments/assets/3bdf639f-701c-4ee0-84a6-f712aa2aad74">
There is an error in the current parsing, days is considered an alias

**Comment by georgesittas** [comment]
This is out of scope, consider using the more standard syntax that uses `INTERVAL`:

```sql
> select cast('2000-08-19' as date) + interval 14 days;
2000-09-02
```

**Comment by liujiwen-up** [comment]
> This is out of scope, consider using the more standard syntax that uses `INTERVAL`:
> 
> ```sql
> > select cast('2000-08-19' as date) + interval 14 days;
> 2000-09-02
> ```

But this is also a way of writing that Hive supports. Don't we consider providing parsing support for these existing ways of writing?

**Comment by georgesittas** [comment]
This particular one is quite non-standard and will be a pain to handle properly. E.g. you have to keep track of all the supported unit keywords and also compare possible aliases to them, which will incur additional overhead. The syntax is also not super straightforward, because if you do `select 14 + 15 days` then `days` is actually an alias, so the types / values of the operands are important in this case. I'm not sure if you can solve this statically without knowing the schemas.
