### ISSUE TITLE
Generator.normalize. uppercase support

### ISSUE THREAD

**Issue by derycck** [tobymao/sqlglot#4167]
In some projects it is conventional that clauses are normalized as lowercase and identifiers are normalized as uppercase.
So when using "sqlglot.expressions.Select" object. sql method. it would be useful to have the option to use the API like this:

```python
expression.sql(
        dialect="bigquery",
        pretty=True,
        normalize="upper"
)
```

Thus ensuring that all identifiers become uppercase.

Today, the normalize parameter is restricted to True/False, being able to only normalize to lowercase:
_"normalize: Whether to normalize identifiers to lowercase. Default: False."_

--
I have already made the change locally and it has met my expectations.
I am opening this discussion so that if accepted, I can open a pullrequest with the adjustment.

**Comment by georgesittas** [comment]
This is already possible, look into `normalize_identifiers. Perhaps what can be done to enhance the generator's API is to make `normalize` actually control the usage of `normalize_identifiers` instead of always lowercasing cc @tobymao.

Closing this as not planned for the time being. Thanks for proposing the change, though.

**Comment by derycck** [comment]
For others readers:
Using dialect as slowflake ensures that identifiers are converted to uppercase, even when dealing with a query to bigquery.

```python
    expression = (sqlglot.optimizer.normalize_identifiers.normalize_identifiers(
            expression, dialect="snowflake"))
```
It works perfectly. Thanks for the tip, George
