### ISSUE TITLE
Covering compilation paths for CHAR_LENGTH, UNICODE, and ISASCII

### ISSUE THREAD

**Issue by pruzko** [tobymao/sqlglot#4233]
Hi,

I am developing an [SQL Injection framework](https://github.com/pruzko/hakuin) and am migrating to sqlglot. There are some SQL functions that I use across several dialects that can be abstracted. If you are interested, I'd implement them directly in sqlglot.

1) number of characters (not bytes) in a string:
```
sqlite: LENGTH(x)
mysql: CHAR_LENGTH(x)
postgres: CHAR_LENGTH(x)
mssql: LENGTH(x)
oracledb: LENGTH(x)
```

2) unicode point for a character:
```
sqlite: unicode(x)
mysql: ord(cast(x as char character set utf32))
postgres: ascii(x)
mssql: unicode(x)
oracledb: ascii(unistr(x))
```

3) is ascii predicate:
```
sqlite: not x glob cast(x'2a5b5e012d7f5d2a' as text)
mysql: not regexp_like(x, '[^[:ascii:]]')
postgres: x ~ '^[[:ascii:]]*$'
mssql: patindex('%[^'+char(0x00)+'-'+char(0x7f)+']%' COLLATE Latin1_General_BIN, x) = 0
oracledb: nvl(regexp_like(x, '^['||chr(1)||'-'||chr(127)||']*$'),1)
```

I noticed you already do [abstractions even when a certain functionality is not natively supported](https://github.com/tobymao/sqlglot/blob/aee76da1cadec242f7428d23999f1752cb0708ca/sqlglot/dialects/dialect.py#L1054). The changes I'd make would be similar to [my last PR](https://github.com/tobymao/sqlglot/pull/4198).

I am rushing with some other duties, but would like to implement this in the future. What are your thoughts?

**Comment by georgesittas** [comment]
Hey @pruzko,

First of all, cool project! Even cooler that you're looking to use SQLGlot in it. :)

We'll be happy to accept well-tested & documented PRs, feel free to send them our way and we'll take a look. One thing to take into consideration when working on the transpiler is that certain operations require type inference to be transpiled correctly. We've a pattern where we use `annotate_types` to achieve this in some places, but without schema it's best-effort. May or may not be relevant to the work you mentioned.

I'll go ahead and close this issue as not planned since we're not really planning to work on these. Thank you for the offer!
