### ISSUE TITLE
Bug In Parsing ANY function from postgres to spark

### ISSUE THREAD

**Issue by dor-bernstein** [tobymao/sqlglot#4298]
**Fully reproducible code snippet**
input:
```python
from sqlglot import parse_one
query = """SELECT col1 from table where ANY(col2) = 'value'"""
parse_one(query, dialect='postgres').sql(dialect='spark')
``` 
output is:
SELECT col1 FROM table WHERE ANY(col2) = 'value'

while the expected output is:
SELECT col1 FROM table WHERE ARRAY_CONTAINS(col2,'value') = true

**Comment by VaggelisD** [comment]
Hey @dor-bernstein, thanks for reporting this.

That's interesting, so afaict the issue here is that in Spark, `ANY` is an aggregate function and thus can't appear in the `WHERE` clause. In Postgres (among other dialecrts), `ANY` is a built-in operator / predicate function. 

Could we somehow generalize the solution here? If i'm not mistaken, the suggested output will only work (1) if `col2` is an array expression and (2) we have an equality operator; What if there was a subquery in `col2`'s place and/or a different operator?

**Comment by dor-bernstein** [comment]
@VaggelisD You are correct. In this case, we can use the exists operator:
1. For subqueries we will need to do:
postgres-query: 
SELECT id 
from employees 
WHERE salary > ANY (SELECT average_salary FROM departments) to:


spark-query:
SELECT id 
from employees 
WHERE EXISTS (
    SELECT 1
    FROM departments d
    WHERE e.salary > d.average_salary
).

2. For the case I presented, we will need to handle to do something like this:
postgres-query:
SELECT col1 from table where ANY(col2) = 'value'

spark-query:
SELECT col1 from table where exists(col2, x -> x = 'value'))

**Comment by VaggelisD** [comment]
Hey @dor-bernstein,

Thanks for the breakdown! I went ahead and implemented a prototype for (2), the `EXISTS` function looks like a solid approach for that matter.
