### ISSUE TITLE
Expected that round-tripping (same dialect) fixes unescaped backslashes?

### ISSUE THREAD

**Issue by dylanscott** [tobymao/sqlglot#4344]
I'm not sure if this is a bug but it seemed strange as it can change the semantics of a query.

In all the dialects I tried, round-tripping through sqlglot will add an extra backslash to an unescaped backslash in a string literal. For example:

```python
from sqlglot import transpile

original_query = r"""
select 
name as raw_name,
REGEXP_REPLACE(name, ' [vV]\d+$','') as unescaped_backslash,
REGEXP_REPLACE(name, ' [vV]\\d+$','') as escaped_backslash,
from values ('foo'), ('bar v1') as t (name)
"""
print("original query", original_query)

(roundtrip,) = transpile(original_query, pretty=True, read="snowflake", identity=True)
print("roundtrip", roundtrip)
```

Note the use of raw Python strings here: I found at least one prior issue (#2236) which seemed to stem from confusion about escaping of Python strings, but in the original context I encountered this these were not Python string literals (the query was read from a file).

Now it seems that in some dialects `original_query` is not syntactically valid at all - BigQuery for example reports "Illegal escape sequence: \d at [3:28]". However in some dialects like Snowflake `original_query` is syntactically valid but has different semantics than the fixed form. [Here](https://docs.snowflake.com/en/sql-reference/functions-regexp#label-regexp-escape-character-caveats) are the Snowflake docs for specifying regexes in single-quoted strings which call out that the backslash sequence `\d` must be escaped `\\d` and round-tripping conceals the bug in the original SQL with the unescaped backslash.

**Comment by VaggelisD** [comment]
Sorry for the incorrect mention, feel free to ignore.

**Comment by georgesittas** [comment]
As you say, the original query here is probably poorly written, relying on unspecified behavior around `\d`. If you wanted to match a `d`, you could omit the backslash altogether. Even though this is accepted by Snowflake, I don't think it's worth tackling right now, because it'd change certain properties in how escapes are handled and the complexity looks unjustified. Happy to continue discussing, but I'm gonna close this for now.

<img width="1034" alt="Screenshot 2024-11-05 at 12 16 48 PM" src="https://github.com/user-attachments/assets/1deb6d31-a526-464b-b197-e199a89c1c86">
