### ISSUE TITLE
Commented conditions are generated incorrectly when wrapped with subqueries

### ISSUE THREAD

**Issue by mkmoisen** [tobymao/sqlglot#4351]
Hello,

This works as expected:

```
from sqlglot import parse_one

parsed = parse_one('''
    select foo
    from bar
    where 1=1
        -- and baz = 5
''')

print(parsed.sql(pretty=True))
```

```
SELECT
  foo
FROM bar
WHERE
  1 = 1 /* and baz = 5 */
```

However wrapping it in a subquery will rearrange the comment to the subquery:

```
from sqlglot import parse_one

parsed = parse_one('''
    select *
    from (
        select foo
        from bar
        where 1=1
            -- and baz = 5
    )
''')
```

```
SELECT
  *
FROM (
  SELECT
    foo
  FROM bar
  WHERE
    1 = 1
) /* and baz = 5 */
```

And wrapping it in a subquery with an alias will remove the comment entirely:

```
from sqlglot import parse_one

parsed = parse_one('''
    select *
    from (
        select foo
        from bar
        where 1=1
            -- and baz = 5
    ) subq
''')

print(parsed.sql(pretty=True))
```

```
SELECT
  *
FROM (
  SELECT
    foo
  FROM bar
  WHERE
    1 = 1
) AS subq
```

Thank you.

**Comment by georgesittas** [comment]
This is low priority for us, attaching comments in the AST is best-effort. One common heuristic that is also used in SQLGlot is that a comment in a line that only comprises whitespace gets attached to the next token. In the 2nd example, that token is the `)` of the subquery and so that explains the behavior you're seeing.

I think to solve this we'd need to update that heuristic and perhaps make it attach the comment to the _previous_ token instead if the next one is a closing delimiter like the `)` here. I'm not sure though if that's consistently reasonable.

We'll be happy to accept PRs, may take a look at the last example later just so that we don't drop the comment.

**Comment by mkmoisen** [comment]
Hi @georgesittas ,

Is this [code](https://github.com/tobymao/sqlglot/blob/87ab8fe9cc4d6d060d8fe8a9c3faf8c47c2c9ed6/sqlglot/tokens.py#L1233) in `tokens.py::Tokenizer::_scan_comment` responsible?

I was searching around in parser.py for a while before I realized that comments simply aren't parsed in parser.py. It seems like it rather takes place in tokens.py.

Would you please explain the rational behind parsing comments in tokens.py instead of parser.py?

I am relatively familiar with parser.py by now, but I'm not up to speed yet on tokens.py.

I'll give it a shot in my subclass and if it works out I will raise a PR.

Thank you.
