### ISSUE TITLE
Eliminating unnecessary CAST() operations

### ISSUE THREAD

**Issue by davlee1972** [tobymao/sqlglot#4374]
There are some major performance hits when unnecessary CAST() operations are introduced.. Is there some way to add something at minimum for strings like 'is_implicit_string_cast_supported' which can be set so CAST() isn't added to the SQL.

Here are some examples:

For the following Abstract SQL expression:

```
  where=Where(
    this=And(
      this=Paren(
        this=And(
          this=GTE(
            this=Column(
              this=Identifier(this=end_date, quoted=False)),
            expression=Cast(
              this=Literal(this=2019-09-04, is_string=True),
              to=DataType(this=Type.DATE, nested=False))),
          expression=LT(
            this=Column(
              this=Identifier(this=end_date, quoted=False)),
            expression=Cast(
              this=Literal(this=2019-09-05, is_string=True),
              to=DataType(this=Type.DATE, nested=False))))),

```

It generates a SQL condition with a CAST().
`
'SELECT cusip AS "cusip", start_date AS "start_date", end_date AS "end_date", purpose AS "purpose", source AS "source", flow AS "flow", flow_usd AS "flow_usd", currency AS "currency" FROM FUND_FLOWS WHERE (end_date >= CAST(\'2019-09-04\' AS DATE) AND end_date < CAST(\'2019-09-05\' AS DATE)) AND (cusip LIKE \'BRTHH%\' AND currency IN (\'USD\', \'GBP\')) LIMIT 10'`

Unfortunately in our testing the above sql statement took 1050 seconds to run..
Without the CAST() it takes 2.5 seconds. This is because when adding a CAST() operator it sends the SQL optimizer down a path where it won't use any indexes on that column since it is technically a compute value being used as a filter.

vs

`'SELECT cusip AS "cusip", start_date AS "start_date", end_date AS "end_date", purpose AS "purpose", source AS "source", flow AS "flow", flow_usd AS "flow_usd", currency AS "currency" FROM FUND_FLOWS WHERE (end_date >= \'2019-09-04\') AND end_date < \'2019-09-05\')) AND (cusip LIKE \'BRTHH%\' AND currency IN (\'USD\', \'GBP\')) LIMIT 10'`

**Comment by georgesittas** [comment]
So this behavior is expected in that the AST structure is preserved in the output. You can't just eliminate the casts without additional context. Having said that, implementing an optimizer rule for this _would_ be helpful, but dealing with implicit coercion is pretty tricky and investigating this for all the supported dialects is definitely out of scope for us, so I'll go ahead and close this ticket.

You can leverage the optimizer infrastructure and implement an internal rule for this if you need it -- look into `canonicalize.py`. My guess is that you'll need to run at least `qualify` and `annotate_types` first before proceeding, because these transformations are type-sensitive.

**Comment by georgesittas** [comment]
Happy to continue discussing here if you wanna investigate & propose an implementation. Even if it's for a subset of the dialects, perhaps it could still be useful.
