### ISSUE TITLE
Incorrect SQL generation with escape characters in string literals

### ISSUE THREAD

**Issue by YieldRay** [tobymao/sqlglot#4492]
```py
import sqlglot
print(sqlglot.__version__) # 25.34.1

sql = r"SELECT '\"'"
print(sql) # SELECT '\"'
ast = sqlglot.parse_one(sql, read='mysql')
print(ast.sql(dialect='mysql')) # SELECT '\\"'
```

Seems that sqlglot adds unnecessary escape character when transforming already escaped quotes (e.g., `\"` becomes `\\"`)

**Comment by VaggelisD** [comment]
I think it's the Python r-string that is interfering with this because the backslashes remain in the string, without it the roundtrip is preserved:

```Python3
>>> import sqlglot
>>> sql = "SELECT '\"'"
>>> print(sql);
SELECT '"'
>>> ast = sqlglot.parse_one(sql, read='mysql')
>>> print(ast.sql(dialect='mysql'));
SELECT '"'
```

**Comment by YieldRay** [comment]
> I think it's the Python r-string that is interfering with this because the backslashes remain in the string, without it the roundtrip is preserved:
> 
> ```python
> >>> import sqlglot
> >>> sql = "SELECT '\"'"
> >>> print(sql);
> SELECT '"'
> >>> ast = sqlglot.parse_one(sql, read='mysql')
> >>> print(ast.sql(dialect='mysql'));
> SELECT '"'
> ```

Yes, use r-string here as I expect the input is
```
SELECT '\"'
```
And it's query result is 

| `"` |
| --- | 
| `"` |

But sqlglot generate this sql
```sql
SELECT '\\"'
```
And the query result is

| `\"` |
| --- | 
| `\"` |

which is not expected

**Comment by georgesittas** [comment]
I think this is an edge case that we intentionally ignore today. In your query, the `\` isn't really needed to escape the `"`, because your string's delimiters are single quotes. It's essentially ignored, i.e. these two are the same:

```
mysql> SELECT '\"';
+---+
| " |
+---+
| " |
+---+
1 row in set (0.00 sec)

mysql> SELECT '"';
+---+
| " |
+---+
| " |
+---+
1 row in set (0.00 sec)
```

Since escapes are a pain to deal with, and this is a weird corner case with questionable utility, I'll go ahead and close this for now. Feel free to take a stab at this or suggest a workaround if you see a simple one.
