### ISSUE TITLE
Unexpected conversion of comments

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#713]
The below statement 
```
SELECT
    * /* hey there */
  FROM v 
```

is auto converted to 
```
SELECT
    * -- hey there
  FROM v 
```

But the following statement
```
SELECT
    * 
  FROM v  -- hey there
```
 
becomes
```
SELECT
    * 
  FROM v /* hey there */
```

on parsing.

**Comment by GeorgeSittas** [comment]
This has to do with the prettifying logic for the FROM clause. The idea is similar to what I said [here](https://github.com/tobymao/sqlglot/issues/712#issuecomment-1317296047), but maybe we can change this for consistency by not using the "flat" argument during formatting @tobymao.

In any case, this is not a serious issue because the output is valid for all dialects currently supported in SQLGlot, so I'm closing this for now and we may implement the above change in the future.
