### ISSUE TITLE
bool_or does not work correctly

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#947]
valid presto input
```
SELECT bool_or(a > 10) FROM asd AS T(a);
```
is changed to
```
SELECT
    logical_or(a > 10)
FROM
    asd AS T(a)
```
WHICH IS NOT EQUIVALENT! Presto does not have logical_or aggregate function.

P.S. in case of `SELECT 1s` or `SELECT 1e` sqlglot also returns not-equivalent output

**Comment by barakalon** [comment]
@evyasonov I'm not sure if you're intending for your comments to sound disrespectful, but they do. For example, adding a "P.S." about a separate issue in each new issue comes off as pestering.

So a friendly reminder - folks have spent countless hours building and maintaining this project _for free_. Ultimately, we fix issues because we enjoy it, not because we are obligated to. A person's negative attitude can kill the joy, making it less likely their issues get fixed.

Also - feel free to contribute fixes for these issues! Your help improving this project would be more than welcome.

_My apologies if I've misread your tone._
