### ISSUE TITLE
Bigquery identifiers can contain unquoted dashes

### ISSUE THREAD

**Issue by williame** [tobymao/sqlglot#969]
https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#unquoted_identifiers

This is regularly encountered in project names.  It is normal for bigquery tables to be namespaced by project and dataset, and for the project to contain dashes.  The following are all equivalent: 

    SELECT * FROM project-1.ds.t
    SELECT * FROM `project-1`.ds.t
    SELECT * FROM `project-1.ds.t`

sqlglot-10.5.3 raises a ParseError "Invalid expression / Unexpected token"

**Comment by GeorgeSittas** [comment]
It's a bit tricky to fix this I think, because `-` is recognized as a minus token in SQLGlot so we'll have ambiguities.

How does this work in BigQuery? E.g. does it allow the following, and if yes, how does it decide whether the projection is a subtraction of `foo` and `bar` or a single identifier `foo-bar`?

```
SELECT foo-bar
```

**Comment by GeorgeSittas** [comment]
We don't plan on fixing this for the time being.

**Comment by tobymao** [comment]
@williame fyi all of these examples should work now as of v15.2.0
