### ISSUE TITLE
Open to adding MEDIUMTEXT and LONGTEXT types?

### ISSUE THREAD

**Issue by earonesty** [tobymao/sqlglot#979]
mysql/sql server support these

will need TYPE_MAPPING to TEXT in all other dialects, imo

tokens/expressions/parser change + mappings + a tests or 2 should be enough, right?

**Comment by tobymao** [comment]
another approach which may be simpler is in mysql to convert longtext into text with a length of 4294967295.

i'm open to either suggestion, i don't think you need any parser changes. since only mysql supports this, you can make the type_mapping more dry by having the base mapping convert longtext into text and only mysql allows longtext

are you planning to make a PR?

**Comment by earonesty** [comment]
cool, thanks!
