### ISSUE TITLE
Snowflake Semi-structured data support

### ISSUE THREAD

**Issue by danfrankj** [tobymao/sqlglot#99]
I believe this would be a bigger change than simply adding a new dialect as new parsing is required for json extraction syntax

Test Cases 
```
SELECT foo:bar

SELECT foo:bar:baz::DATE

SELECT foo:bar[0]

SELECT foo:bar.baz
```

Ref:
https://docs.snowflake.com/en/user-guide/querying-semistructured.html#traversing-semi-structured-data

**Comment by tobymao** [comment]
this is not too difficult, just need to support single semicolon

**Comment by tobymao** [comment]
@danfrankj i'm reading through snowflake docs and i don't quite understand the difference between : and .

can i just convert : -> .? this is a one line change

**Comment by NodeJSmith** [comment]
@tobymao I know this is closed, but I'm hitting the same issue currently with version 10.5.10. Happy to provide more information and/or to open a new issue for this. Below is a screenshot of the issue - I imagine it's because there are double quotes, since that is what seems to differ between my example and the example provided by @danfrankj 

![image](https://user-images.githubusercontent.com/8505845/215353532-87db6dac-1e15-47d2-b7c3-6ca0f57ab0ad.png)

**Comment by tobymao** [comment]
please open a new issue thanks!

**Comment by tobymao** [comment]
@NodeJSmith i tried to recreate your error from your screen shot but it seems to work

```
python -m sqlglot 'select generated_features:"uws.rcu"' --read=snowflake
SELECT
  "generated_features"['uws.rcu']
```

**Comment by tobymao** [comment]
don't forget to pass the read dialect in as snowflake

**Comment by NodeJSmith** [comment]
@tobymao fudge, I totally forgot to do that 🤦‍♀️ I'll try it today, I imagine that will fix it. Sorry for the false alarm
